version: '3.8'

services:
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: "/app"
    tty: true
    environment:
      VUE_APP_API_ENDPOINT: ${VUE_APP_API_ENDPOINT} 
    entrypoint: npm run serve
