up:
	docker-compose --env-file .env.dev up -d

up-prod:
	docker-compose up -d

kill:
	docker-compose kill

restart: kill up

log:
	docker-compose logs -f

build:
	docker-compose build

exec:
	docker-compose exec vue sh
