version: "3.8"

services:
  mysql:
    container_name: "mysql"
    networks:
      - develop_homete_network
    image: mysql:8.0.27
    volumes:
      - develop_mysql_volume:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d/mysql.conf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  python:
    container_name: "python3"
    networks:
      - develop_homete_network
    build:
      context: .
      dockerfile: ../../Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    working_dir: "/usr/src/app"
    tty: true
    environment:
      FIREBASE_KEY: ${FIREBASE_KEY}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      FLASK_APP: run.py
      FRONTEND_URL: ${FRONTEND_URL}
      SECRET_KEY: ${SECRET_KEY}
      DOMAIN: ${DOMAIN}
    entrypoint: python run.py

networks:
  develop_homete_network:
    external: true

volumes:
  develop_mysql_volume:
