version: "3.8"

services:
  redis:
    container_name: "redis"
    restart: always
    networks:
      - homete_network
    image: "redis"
    volumes:
      - redis_volume:/data
    command:
      redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    container_name: "postgres"
    restart: always
    networks:
      - homete_network
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  python:
    container_name: "python3"
    restart: always
    networks:
      - homete_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../:/usr/src/app/
    working_dir: "/usr/src/app"
    tty: true
    environment:
      FLASK_APP: run.py
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      SALT: ${SALT}

networks:
  homete_network:

volumes:
  postgres_volume:
  redis_volume: