version: "3.8"

services:
  redis:
    container_name: "redis"
    restart: always
    networks:
      - homete_network
    image: "redis"
    volumes:
      - redis_volume:/data
    command:
      redis-server --requirepass ${REDIS_PASSWORD}

  mysql:
    container_name: "mysql"
    restart: always
    networks:
      - homete_network
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d/mysql.conf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin 

  python:
    container_name: "python3"
    restart: always
    networks:
      - homete_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    working_dir: "/usr/src/app"
    tty: true
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      FLASK_APP: run.py
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      SALT: ${SALT}
      DOMAIN: ${DOMAIN}
    entrypoint: python run.py

networks:
  homete_network:

volumes:
  mysql_volume:
  redis_volume: