up:
	docker-compose --env-file .env.dev -f docker-compose.dev.yml up -d

up-prod:
	docker-compose up -d

down:
	docker-compose down

kill:
	docker-compose kill

restart: kill up

log:
	docker-compose logs -f
