"""empty message

Revision ID: 20048f1dbfae
Revises: b0d8071fe30c
Create Date: 2021-12-28 22:02:44.802545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20048f1dbfae'
down_revision = 'b0d8071fe30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reactions',
    sa.Column('user_reaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=15), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_reaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reactions')
    # ### end Alembic commands ###
