"""empty message

Revision ID: 48c12bf2a45f
Revises: 5aec0a1a00e4
Create Date: 2022-11-13 13:52:19.903662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c12bf2a45f'
down_revision = '5aec0a1a00e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('head', sa.String(length=15), nullable=True),
    sa.Column('face', sa.String(length=15), nullable=True),
    sa.Column('facialHair', sa.String(length=15), nullable=True),
    sa.Column('accessories', sa.String(length=15), nullable=True),
    sa.Column('skinColor', sa.String(length=15), nullable=True),
    sa.Column('clothingColor', sa.String(length=15), nullable=True),
    sa.Column('hairColor', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('face_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('contents', sa.String(length=400), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reaction_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_reactions')
    op.drop_table('posts')
    op.drop_table('post_reactions')
    op.drop_table('post_faces')
    # ### end Alembic commands ###
