"""empty message

Revision ID: 5aec0a1a00e4
Revises: 20048f1dbfae
Create Date: 2022-11-08 11:11:42.494048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aec0a1a00e4'
down_revision = '20048f1dbfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_email', table_name='users')
    op.drop_table('users')
    op.drop_table('user_reactions')
    op.drop_table('homete_posts')
    op.drop_table('post_reactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reactions',
    sa.Column('reaction_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reaction', mysql.VARCHAR(collation='utf8mb4_bin', length=10), nullable=True),
    sa.Column('reaction_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('reaction_id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('homete_posts',
    sa.Column('post_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_bin', length=15), nullable=True),
    sa.Column('post_content', mysql.VARCHAR(collation='utf8mb4_bin', length=100), nullable=True),
    sa.Column('anonymous', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('post_id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_reactions',
    sa.Column('user_reaction_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_bin', length=15), nullable=True),
    sa.Column('reaction', mysql.VARCHAR(collation='utf8mb4_bin', length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_reaction_id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_bin', length=15), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_bin', length=15), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(collation='utf8mb4_bin', length=256), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_bin', length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_email', 'users', ['user_email'], unique=False)
    # ### end Alembic commands ###
