"""empty message

Revision ID: 5de21e093929
Revises: 
Create Date: 2022-11-17 13:09:13.133915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de21e093929'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=256), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('contents', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('head', sa.String(length=15), nullable=True),
    sa.Column('face', sa.String(length=15), nullable=True),
    sa.Column('facialhair', sa.String(length=15), nullable=True),
    sa.Column('accessories', sa.String(length=15), nullable=True),
    sa.Column('skincolor', sa.String(length=15), nullable=True),
    sa.Column('clothingcolor', sa.String(length=15), nullable=True),
    sa.Column('haircolor', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='fk_posts_user_email'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_reaction_posts_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=256), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_user_reasction_posts_id'),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='fk_user_reaction_posts_user_email'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reactions')
    op.drop_table('post_reactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
