"""empty message

Revision ID: 7f7f2de68228
Revises: 95f1da6f2d95
Create Date: 2023-01-18 23:27:26.083844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f7f2de68228'
down_revision = '95f1da6f2d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('first_name', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('last_name', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_posts_posts_first_name_id', 'posts', 'posts_name', ['first_name'], ['id'])
    op.create_foreign_key('fk_posts_posts_second_name_id', 'posts', 'posts_name', ['last_name'], ['id'])
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_bin', length=15), nullable=True))
    op.drop_constraint('fk_posts_posts_second_name_id', 'posts', type_='foreignkey')
    op.drop_constraint('fk_posts_posts_first_name_id', 'posts', type_='foreignkey')
    op.drop_column('posts', 'last_name')
    op.drop_column('posts', 'first_name')
    # ### end Alembic commands ###
