"""empty message

Revision ID: 914cae247f95
Revises: 7f7f2de68228
Create Date: 2023-01-27 11:09:25.817391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '914cae247f95'
down_revision = '7f7f2de68228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'contents',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=400),
               type_=sa.String(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'contents',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
