"""empty message

Revision ID: a86ea50054db
Revises: 39c3a7528bf0
Create Date: 2021-12-20 22:40:22.009998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a86ea50054db'
down_revision = '39c3a7528bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homete_posts', sa.Column('anonymous', sa.Boolean(), nullable=True))
    op.add_column('homete_posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('homete_posts', 'delete_at')
    op.add_column('post_reactions', sa.Column('reaction_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('post_reactions', 'id')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'delete_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'deleted_at')
    op.add_column('post_reactions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('post_reactions', 'reaction_id')
    op.add_column('homete_posts', sa.Column('delete_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('homete_posts', 'deleted_at')
    op.drop_column('homete_posts', 'anonymous')
    # ### end Alembic commands ###
