"""empty message

Revision ID: b0d8071fe30c
Revises: 
Create Date: 2021-12-22 22:27:10.277603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d8071fe30c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homete_posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=15), nullable=True),
    sa.Column('post_content', sa.String(length=100), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('post_reactions',
    sa.Column('reaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=15), nullable=False),
    sa.Column('user_name', sa.String(length=15), nullable=True),
    sa.Column('user_email', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('post_reactions')
    op.drop_table('homete_posts')
    # ### end Alembic commands ###
