"""empty message

Revision ID: f5ee95ee8cf5
Revises: 5de21e093929
Create Date: 2022-11-17 13:37:49.043364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ee95ee8cf5'
down_revision = '5de21e093929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_reaction_posts_id'),
    sa.ForeignKeyConstraint(['reaction'], ['reactions.reaction'], name='fk_post_reasction_reaction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=256), nullable=True),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_user_reasction_posts_id'),
    sa.ForeignKeyConstraint(['reaction'], ['reactions.reaction'], name='fk_user_reasction_reaction'),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='fk_user_reaction_posts_user_email'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reactions')
    op.drop_table('post_reactions')
    # ### end Alembic commands ###
