name: Deploy to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VUE_APP_API_ENDPOINT: ${{ secrets.VUE_APP_API_ENDPOINT }}
          VUE_APP_FIRE_BASE_API_KEY: ${{ secrets.VUE_APP_FIRE_BASE_API_KEY }}
          VUE_APP_FIRE_BASE_APP_ID: ${{ secrets.VUE_APP_FIRE_BASE_APP_ID }}
          VUE_APP_FIRE_BASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIRE_BASE_AUTH_DOMAIN }}
          VUE_APP_FIRE_BASE_MEASUREMENT_ID: ${{ secrets.VUE_APP_FIRE_BASE_MEASUREMENT_ID }}
          VUE_APP_FIRE_BASE_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIRE_BASE_MESSAGING_SENDER_ID }}
          VUE_APP_FIRE_BASE_PROJECT_ID: ${{ secrets.VUE_APP_FIRE_BASE_PROJECT_ID }}
          VUE_APP_FIRE_BASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIRE_BASE_STORAGE_BUCKET }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-1

      - name: Remove existing files from S3
        run: aws s3 rm s3://homete-bucket --recursive

      - name: Upload files to S3
        run: aws s3 sync dist s3://homete-bucket

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
